name: Release PR

on:
  push:
    branches:
      - master
jobs:
  release-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        with:
          release-type: node
          package-name: '@byteinspire/inspirecloud'
